name: Scrape Ontario Reign Roster

on:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at noon UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run scraper
        run: ruby scrape_reign.rb

      - name: Commit updated files
        run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "Update roster and dependencies" || echo "No changes to commit"
            git push
